 const labels =  {
     temp_deletion_error: 'Error deleting temp files',
     collect_errors: 'Collect errors',
     help_us_improve: 'Help us improve our app',
     view_on: 'View on',
     edit: 'Edit',
     invite: 'Invite',
     edit_remote_entries: 'Edit Remote Entries',
     bookmarks_loading_error: 'Error loading bookmarks',
     account_email_confirm_before: 'Please confirm you would like the account with email',
     account_email_confirm_after: 'to be removed from our systems.',
     account_deletion_team_will_contact: 'The Epicollect5 Team will contact you about the progress of the account deletion.',
     account_deletion_request_sent: 'Account Deletion Request sent.',
     danger: 'Danger',
     delete_account: 'Delete Account',
     profile: 'Profile',
     address: 'Address',
     exit: 'Exit',
     editing_branches_pwa: 'Please note: to edit existing branch entries you must use the Epicollect5 Data Viewer.',
     format: 'Format',
     clear_filters: 'Clear Filters',
     invalid_value: 'Invalid value',
     search: 'Search',
     are_you_sure: 'Are you sure?',
     delete: 'Delete',
     share: 'Share',
     locate: 'Locate',
     or: 'OR',
     check_email: 'Check your email',
     enter_password: 'Please enter password for verification',
     code_was_sent: 'A code was sent for verification',
     account_exists: 'Account already exists',
     login_with_email: 'Login With Email',
     passwordless_teaser: 'We will send you a code to your inbox',
     enter_code: 'Enter code',
     send: 'Send',
     all: 'All',
     incomplete: 'Incomplete',
     has_errors: 'Error',
     wrong_range: 'Range Invalid',
     invalid_entries: 'Invalid Entries',
     add_branch: 'Add Branch',
     status: 'Status',
     from: 'From',
     to: 'To',
     reset: 'Reset',
     show: 'Show',
     show_filters: 'Show filters on entries list',
     hide_filters: 'Hide filters',
     filters: 'Filters',
     filter_by_title: 'Filter by title',
     no_hits_found: 'Nothing found',
     not_available: 'Not available',
     name: 'Name',
     description: 'Description',
     small_description: 'Small Description',
     homepage: 'Homepage',
     project_info: 'Project Info',
     version: 'Version',
     advanced_settings: 'Advanced',
     ok: 'Ok',
     download_remote_entries: 'Download remote entries',
     remote_entry: 'Remote entry',
     entry: 'Entry',
     download_warning: 'This will remove any remote entries you already have for this project on your device. Continue?',
     text_size: 'Text size',
     accessibility: 'Accessibility',
     type_answer_here: 'Type answer here...',
     confirm_answer_here: 'Confirm answer here...',
     confirm: 'Confirm',
     help: 'Help',
     user_guide: 'User Guide',
     hi: 'Hi',
     prev: 'Prev',
     next: 'Next',
     quit: 'Quit',
     save: 'Save',
     save_entry: 'Save entry',
     quit_entry: 'Quit',
     save_branch_entry: 'Save branch',
     quit_branch: 'Quit',
     login: 'Login',
     logout: 'Logout',
     scan: 'Scan',
     entries: 'entries',
     branch_entries: 'Branch entries',
     update_location: 'Update location',
     not_located_yet: 'Not set yet',
     latitude: 'Latitude',
     longitude: 'Longitude',
     accuracy: 'Accuracy',
     unknown_error: 'Unknown error',
     db_created: 'Epicollect5 database ready',
     db_not_created: 'Error creating Epicollect5 database!',
     locating: 'Locating',
     wait: 'Please Wait...',
     saving: 'Saving...',
     loading: 'Loading...',
     acquiring_position: 'Acquiring position',
     location_acquired: 'Location acquired',
     location_fail: 'Not able to locate!',
     location_service_fail: 'Location Services and Permissions must both be enabled for Epicollect5 to get the device location.',
     ios_location_permission_denied: 'Epicollect5 location permission was denied, please enable it in Settings',
     ios_location_permission_restricted: 'Epicollect5 location permission is restricted for the current user',
     android_location_permission_denied_always: 'Epicollect5 location permission is denied, please grant it. It is not possible to use Location Services without appropriate permission',
     no_projects_found: 'No projects found',
     date_selected_is: 'The date selected is: ',
     time_selected_is: 'The time selected is: ',
     preparing_scanner: 'Preparing scanner',
     failed_because: 'Failed because: ',
     stop: 'Stop',
     play: 'Play',
     record: 'Record',
     recording: 'Recording',
     playing: 'Playing',
     recording_audio: 'Recording audio...',
     playing_audio: 'Playing audio...',
     shoot: 'Shoot',
     video_saved: 'Video saved',
     audio_saved: 'Audio saved',
     cannot_save_file: 'Cannot save the file! Please retry',
     file_available: 'File available',
     uploading: 'Uploading',
     uploading_entries: 'Uploading Entries',
     loading_project: 'Loading project',
     loading_entries: 'Loading entries',
     loading_entry: 'Loading entry',
     no_entries_found: 'No entries found',
     no_errors_found: 'No errors found',
     pick_possible_answer: 'Pick possible answer',
     permission_denied: 'Permission denied',
     location_not_available: 'Location is not available, Epicollect5 will not be able to locate you.',
     min: 'Min',
     max: 'Max',
     no_answer_given: 'No answer given ',
     error: 'Error',
     delete_project: 'Delete Project',
     delete_entry: 'Delete Entry',
     delete_all_entries: 'Delete All Entries',
     delete_synced_entries: 'Delete Synced Entries',
     delete_unsynced_entries: 'Delete Unsynced Entries',
     bookmark: 'Bookmark',
     bookmark_title: 'Add a bookmark title',
     close: 'Close',
     add_bookmark: 'Add Bookmark',
     add_entry: 'Add Entry',
     type_hint: 'Type here',
     menu: 'Menu',
     project_options: 'Project Options',
     upload_entries: 'Upload Entries',
     download_entries: 'Download Entries',
     unsync_all_entries: 'Unsync All Entries',
     export_all_entries: 'Export All Entries',
     unsynced: 'Unsynced',
     unsync_entry: 'Unsync Entry',
     bookmark_page: 'Bookmark Page',
     remove_bookmark: 'Remove Bookmark',
     sort: 'Sort',
     newest: 'Newest',
     oldest: 'Oldest',
     sign_in: 'Signing in',
     no_bookmarks_found: 'No bookmarks found',
     my_bookmarks: 'My Bookmarks',
     export_entries: 'Export json entries',
     exporting: 'Exporting',
     exporting_success: 'All Entries Exported!',
     exported_to: 'Exported to: ',
     deleting_project: 'Deleting Project',
     deleting_entries: 'Deleting Entries',
     entry_deleted: 'Entry Deleted',
     file_deleted: 'File Deleted',
     email: 'Email',
     password: 'Password',
     ldap_username: 'Ldap Username',
     ldap_password: 'Ldap Password',
     google_sign_in: 'Google Sign In',
     upload_data: 'Upload data',
     upload_photos: 'Upload photos',
     upload_videos: 'Upload videos',
     upload_audios: 'Upload audio',
     uploading_photos: 'Uploading photos',
     uploading_videos: 'Uploading videos',
     uploading_audios: 'Uploading audio',
     all_entries_uploaded: 'All Entries Uploaded',
     file_uploaded: 'File uploaded',
     entries_errors: 'Some of the entries have errors',
     children: 'Children',
     search_for_project: 'Search for a project',
     add_project: 'Add Project',
     projects: 'Projects',
     delete_branch_entry: 'Delete Branch Entry',
     back: 'Back',
     settings: 'Settings',
     server_url: 'Server Url',
     server_url_placeholder: 'eg http://www.mydomain.com',
     downloads: 'Downloads',
     download: 'Download',
     warning: 'Warning',
     missing_permission: 'You must grant the appropriate permission to perform this action',
     please_wait: 'Please Wait...',
     server_url_error: 'Server not found, please check your server URL in the settings',
     quitting: 'Quitting',
     cancel: 'Cancel',
     project_outdated: 'Form has been updated.',
     update_project: 'Update form on your device?',
     project_updated: 'Forms updated.',
     updating_project: 'Updating Forms.',
     updating_entries: 'Updating entries.',
     check_for_updates: 'Check for Form Updates',
     checking_for_updates: 'Checking for updates...',
     loading_projects: 'Loading Projects',
     incomplete_entry: 'This entry is incomplete',
     entry_completed: 'Entry completed',
     unsynced_entries: 'Unsynced entries',
     unsynced_entry: 'Entry unsynced.',
     sync_now: 'Upload',
     save_entry_and_sync: 'Save entry and Sync',
     check_entries: 'Check entries',
     connect_to_internet_to_upload: 'Please connect to the internet to upload entries.',
     entries_errors_page: 'Entries with Errors',
     check_entries_below: 'Check the entries below for errors.',
     branch: 'Branch',
     pattern: 'Pattern',
     required: '* This field is required',
     entries_media_errors: 'Could not upload your media. Please try again later.',
     db_updated: 'Database updated.',
     downloading_entries: 'Downloading entries',
     all_entries_downloaded: 'All Entries Downloaded.',
     unsaved_branch_entries: 'Unsaved Branch Entries',
     save_now: 'Save Now',
     incomplete_entries: 'You have incomplete entries which cannot be uploaded.',
     load_more: 'Load More',
     take: 'Take',
     pick: 'Pick',
     collected_on: 'Collected on ',
     dismiss: 'Dismiss'
 };